CREATE TABLE USUARIO (
   ID BIGINT IDENTITY(1, 1) NOT NULL,
   LOGIN VARCHAR(255) NOT NULL,
   SENHA VARCHAR(255) NOT NULL,
   ADMIN BIT NOT NULL,
   CONSTRAINT USUARIO_PK PRIMARY KEY (ID),
   CONSTRAINT USUARIO_UC UNIQUE(LOGIN) 
);