CREATE TABLE VENDA (
   ID BIGINT IDENTITY(1, 1) NOT NULL,
   CLIENTE_ID BIGINT NOT NULL,
   DATA_VENDA DATE NOT NULL,
   VALOR_VENDA NUMERIC(20,2) NOT NULL,
   CONSTRAINT VENDA_PK PRIMARY KEY (ID),
   CONSTRAINT VENDA_CLIENTE_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) 
);