CREATE TABLE ITEM_VENDA (
   ID BIGINT IDENTITY(1, 1) NOT NULL,
   VENDA_ID BIGINT NOT NULL,
   PRODUTO_ID BIGINT NOT NULL,
   QUANTIDADE INTEGER NOT NULL,
   CONSTRAINT ITEM_VENDA_PK PRIMARY KEY (ID),
   CONSTRAINT ITEM_VENDA_VENDA_FK FOREIGN KEY (VENDA_ID) REFERENCES VENDA(ID),
   CONSTRAINT ITEM_VENDA_PRODUTO_FK FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO(ID) 
);